// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
        // return web; // Use web options for linux
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3AslLT2SvFcxy7zql50H3OVz-l04xImg',
    appId: '1:588881844642:web:5a83f7d447c3a7fc57fafb',
    messagingSenderId: '588881844642',
    projectId: 'amategeko-c9f7a',
    authDomain: 'amategeko-c9f7a.firebaseapp.com',
    storageBucket: 'amategeko-c9f7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1RGhDauBMaQWeShjCx9AGKFbtQnmbD4',
    appId: '1:588881844642:android:b125c2590fdf6eec57fafb',
    messagingSenderId: '588881844642',
    projectId: 'amategeko-c9f7a',
    storageBucket: 'amategeko-c9f7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwPwrD6DJwzN_IDWfjJM3QC4ZYSHnZME',
    appId: '1:588881844642:ios:01b583812c58c3a257fafb',
    messagingSenderId: '588881844642',
    projectId: 'amategeko-c9f7a',
    storageBucket: 'amategeko-c9f7a.firebasestorage.app',
    iosClientId: '588881844642-0phe3aif3tj1pjq9ji4m2fp0pngu6cha.apps.googleusercontent.com',
    iosBundleId: 'com.prorw.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwPwrD6DJwzN_IDWfjJM3QC4ZYSHnZME',
    appId: '1:588881844642:ios:01b583812c58c3a257fafb',
    messagingSenderId: '588881844642',
    projectId: 'amategeko-c9f7a',
    storageBucket: 'amategeko-c9f7a.firebasestorage.app',
    iosClientId: '588881844642-0phe3aif3tj1pjq9ji4m2fp0pngu6cha.apps.googleusercontent.com',
    iosBundleId: 'com.prorw.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3n6PH-C6lcYeKKN-KAWFIpgsRw-2A6U0',
    appId: '1:588881844642:web:7c03c1cd94277bc557fafb',
    messagingSenderId: '588881844642',
    projectId: 'amategeko-c9f7a',
    authDomain: 'amategeko-c9f7a.firebaseapp.com',
    storageBucket: 'amategeko-c9f7a.firebasestorage.app',
  );

}